### ISSUE TITLE
Problem with Deserializing Response

### ISSUE THREAD

**Issue by xqlim1996** [limxuanyu127/facility-booking#2]
Encountered bugs when testing Deserializing TestResponse:

Test
```
public class Deserializer {
    public static void main(String[] args) {
        TestResponse r = new TestResponse();
        ByteBuffer bb = ByteBuffer.allocate(2000);
        Serializer.serializeObject(r, bb);
        bb.flip();
        Object o = deserializeObject(bb);
        System.out.println(o.getClass().getName());
        System.out.println(((TestResponse) o).testString);
        System.out.println(((TestResponse) o).testInt);
//        System.out.println(((TestRequest) o).testList);
//        System.out.println(((TestRequest) o).testNestedList);
    }
```

Stack Trace:
```
Exception in thread "main" java.lang.IllegalArgumentException: Can not set int field commons.responses.TestResponse.testInt to null value
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeIntegerFieldAccessorImpl.set(UnsafeIntegerFieldAccessorImpl.java:80)
	at java.base/java.lang.reflect.Field.set(Field.java:793)
	at commons.Deserializer.deserializeObject(Deserializer.java:53)
	at commons.Deserializer.main(Deserializer.java:19)

FAILURE: Build failed with an exception.
```

**Comment by sith0008** [comment]
the problem is with `int` vs `Integer`. The current serializer/deserializer works with `Integer`.

for now, we can standardize to use the `Integer` class instead of the `int` primitive for our request/response field types. if got time, i find a workaround to support `int`

**Comment by xqlim1996** [comment]
ok sounds good, lets use Integer for now then thanks!
